# Generated by Django 2.1.2 on 2018-11-07 09:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Страница')),
                ('metakey', models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова')),
                ('metadesc', models.CharField(blank=True, max_length=255, verbose_name='Мета описание')),
                ('page_link', models.SlugField(blank=True, max_length=150)),
                ('page_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст страницы')),
                ('position', models.SmallIntegerField(verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы',
                'db_table': 'pages',
                'ordering': ['position'],
            },
        ),
    ]
